# Generated by Django 4.2 on 2023-05-14 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.IntegerField(unique=True)),
                ('stud_name', models.CharField(max_length=255)),
                ('stud_gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(max_length=7)),
                ('level', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=255)),
                ('mobileNumber', models.CharField(max_length=12)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.department')),
            ],
        ),
    ]
