# Generated by Django 3.2.12 on 2023-05-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20230519_1427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userSeif3ars',
        ),
    ]
